dist: focal
install:
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libpython3-dev npm nodejs sqlite3 libsqlite3-dev uuid uuid-dev libcurl4-openssl-dev automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
- mkdir thrift_dir
- cp depend_docker/thrift-0.14.1.tar.gz ./thrift_dir/
- pushd thrift_dir
- tar xf thrift-0.14.1.tar.gz
- pushd thrift-0.14.1
- ./configure --prefix=/usr --without-ruby --without-java --without-go --without-erlang --without-perl --without-qt5 --without-lua --without-php --without-nodejs --without-php_extension && make -j 8 && sudo make install
- popd
- popd

script: 
- ./build.sh -bf -m build

before_deploy:
  - git config --local user.name "marklion"
  - git config --local user.email "marklion@sina.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  skip_cleanup: true
  file: "$TRAVIS_BUILD_DIR/build/install.sh"
  api_key:
    secure: "$API_KEY"