/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "idl_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




gen_exp::~gen_exp() noexcept {
}


void gen_exp::__set_msg(const std::string& val) {
  this->msg = val;
}
std::ostream& operator<<(std::ostream& out, const gen_exp& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t gen_exp::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->msg);
          this->__isset.msg = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t gen_exp::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("gen_exp");

  xfer += oprot->writeFieldBegin("msg", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->msg);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(gen_exp &a, gen_exp &b) {
  using ::std::swap;
  swap(a.msg, b.msg);
  swap(a.__isset, b.__isset);
}

gen_exp::gen_exp(const gen_exp& other0) : TException() {
  msg = other0.msg;
  __isset = other0.__isset;
}
gen_exp& gen_exp::operator=(const gen_exp& other1) {
  msg = other1.msg;
  __isset = other1.__isset;
  return *this;
}
void gen_exp::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "gen_exp(";
  out << "msg=" << to_string(msg);
  out << ")";
}

const char* gen_exp::what() const noexcept {
  try {
    std::stringstream ss;
    ss << "TException - service has thrown: " << *this;
    this->thriftTExceptionMessageHolder_ = ss.str();
    return this->thriftTExceptionMessageHolder_.c_str();
  } catch (const std::exception&) {
    return "TException - service has thrown: gen_exp";
  }
}


user_info::~user_info() noexcept {
}


void user_info::__set_user_id(const int64_t val) {
  this->user_id = val;
}

void user_info::__set_name(const std::string& val) {
  this->name = val;
}

void user_info::__set_logo(const std::string& val) {
  this->logo = val;
}

void user_info::__set_company(const std::string& val) {
  this->company = val;
}

void user_info::__set_buyer(const bool val) {
  this->buyer = val;
}

void user_info::__set_phone(const std::string& val) {
  this->phone = val;
}
std::ostream& operator<<(std::ostream& out, const user_info& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t user_info::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->user_id);
          this->__isset.user_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->logo);
          this->__isset.logo = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->company);
          this->__isset.company = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->buyer);
          this->__isset.buyer = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->phone);
          this->__isset.phone = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t user_info::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("user_info");

  xfer += oprot->writeFieldBegin("user_id", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->user_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("logo", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->logo);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("company", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->company);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("buyer", ::apache::thrift::protocol::T_BOOL, 5);
  xfer += oprot->writeBool(this->buyer);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("phone", ::apache::thrift::protocol::T_STRING, 6);
  xfer += oprot->writeString(this->phone);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(user_info &a, user_info &b) {
  using ::std::swap;
  swap(a.user_id, b.user_id);
  swap(a.name, b.name);
  swap(a.logo, b.logo);
  swap(a.company, b.company);
  swap(a.buyer, b.buyer);
  swap(a.phone, b.phone);
  swap(a.__isset, b.__isset);
}

user_info::user_info(const user_info& other2) {
  user_id = other2.user_id;
  name = other2.name;
  logo = other2.logo;
  company = other2.company;
  buyer = other2.buyer;
  phone = other2.phone;
  __isset = other2.__isset;
}
user_info& user_info::operator=(const user_info& other3) {
  user_id = other3.user_id;
  name = other3.name;
  logo = other3.logo;
  company = other3.company;
  buyer = other3.buyer;
  phone = other3.phone;
  __isset = other3.__isset;
  return *this;
}
void user_info::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "user_info(";
  out << "user_id=" << to_string(user_id);
  out << ", " << "name=" << to_string(name);
  out << ", " << "logo=" << to_string(logo);
  out << ", " << "company=" << to_string(company);
  out << ", " << "buyer=" << to_string(buyer);
  out << ", " << "phone=" << to_string(phone);
  out << ")";
}


driver_info::~driver_info() noexcept {
}


void driver_info::__set_name(const std::string& val) {
  this->name = val;
}

void driver_info::__set_phone(const std::string& val) {
  this->phone = val;
}
std::ostream& operator<<(std::ostream& out, const driver_info& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t driver_info::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->phone);
          this->__isset.phone = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t driver_info::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("driver_info");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("phone", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->phone);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(driver_info &a, driver_info &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.phone, b.phone);
  swap(a.__isset, b.__isset);
}

driver_info::driver_info(const driver_info& other4) {
  name = other4.name;
  phone = other4.phone;
  __isset = other4.__isset;
}
driver_info& driver_info::operator=(const driver_info& other5) {
  name = other5.name;
  phone = other5.phone;
  __isset = other5.__isset;
  return *this;
}
void driver_info::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "driver_info(";
  out << "name=" << to_string(name);
  out << ", " << "phone=" << to_string(phone);
  out << ")";
}


stuff_detail::~stuff_detail() noexcept {
}


void stuff_detail::__set_name(const std::string& val) {
  this->name = val;
}

void stuff_detail::__set_last(const std::string& val) {
  this->last = val;
}

void stuff_detail::__set_price(const int64_t val) {
  this->price = val;
}

void stuff_detail::__set_company(const std::string& val) {
  this->company = val;
}

void stuff_detail::__set_type_id(const int64_t val) {
  this->type_id = val;
}

void stuff_detail::__set_saling(const bool val) {
  this->saling = val;
}
std::ostream& operator<<(std::ostream& out, const stuff_detail& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t stuff_detail::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->last);
          this->__isset.last = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->price);
          this->__isset.price = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->company);
          this->__isset.company = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->type_id);
          this->__isset.type_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->saling);
          this->__isset.saling = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t stuff_detail::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("stuff_detail");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("last", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->last);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("price", ::apache::thrift::protocol::T_I64, 3);
  xfer += oprot->writeI64(this->price);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("company", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->company);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type_id", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->type_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("saling", ::apache::thrift::protocol::T_BOOL, 6);
  xfer += oprot->writeBool(this->saling);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(stuff_detail &a, stuff_detail &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.last, b.last);
  swap(a.price, b.price);
  swap(a.company, b.company);
  swap(a.type_id, b.type_id);
  swap(a.saling, b.saling);
  swap(a.__isset, b.__isset);
}

stuff_detail::stuff_detail(const stuff_detail& other6) {
  name = other6.name;
  last = other6.last;
  price = other6.price;
  company = other6.company;
  type_id = other6.type_id;
  saling = other6.saling;
  __isset = other6.__isset;
}
stuff_detail& stuff_detail::operator=(const stuff_detail& other7) {
  name = other7.name;
  last = other7.last;
  price = other7.price;
  company = other7.company;
  type_id = other7.type_id;
  saling = other7.saling;
  __isset = other7.__isset;
  return *this;
}
void stuff_detail::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "stuff_detail(";
  out << "name=" << to_string(name);
  out << ", " << "last=" << to_string(last);
  out << ", " << "price=" << to_string(price);
  out << ", " << "company=" << to_string(company);
  out << ", " << "type_id=" << to_string(type_id);
  out << ", " << "saling=" << to_string(saling);
  out << ")";
}


user_apply::~user_apply() noexcept {
}


void user_apply::__set_name(const std::string& val) {
  this->name = val;
}

void user_apply::__set_phone(const std::string& val) {
  this->phone = val;
}

void user_apply::__set_logo(const std::string& val) {
  this->logo = val;
}

void user_apply::__set_apply_id(const int64_t val) {
  this->apply_id = val;
}

void user_apply::__set_status(const int64_t val) {
  this->status = val;
}
std::ostream& operator<<(std::ostream& out, const user_apply& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t user_apply::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->phone);
          this->__isset.phone = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->logo);
          this->__isset.logo = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->apply_id);
          this->__isset.apply_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t user_apply::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("user_apply");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("phone", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->phone);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("logo", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->logo);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("apply_id", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->apply_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(user_apply &a, user_apply &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.phone, b.phone);
  swap(a.logo, b.logo);
  swap(a.apply_id, b.apply_id);
  swap(a.status, b.status);
  swap(a.__isset, b.__isset);
}

user_apply::user_apply(const user_apply& other8) {
  name = other8.name;
  phone = other8.phone;
  logo = other8.logo;
  apply_id = other8.apply_id;
  status = other8.status;
  __isset = other8.__isset;
}
user_apply& user_apply::operator=(const user_apply& other9) {
  name = other9.name;
  phone = other9.phone;
  logo = other9.logo;
  apply_id = other9.apply_id;
  status = other9.status;
  __isset = other9.__isset;
  return *this;
}
void user_apply::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "user_apply(";
  out << "name=" << to_string(name);
  out << ", " << "phone=" << to_string(phone);
  out << ", " << "logo=" << to_string(logo);
  out << ", " << "apply_id=" << to_string(apply_id);
  out << ", " << "status=" << to_string(status);
  out << ")";
}


plan_confirm_info::~plan_confirm_info() noexcept {
}


void plan_confirm_info::__set_timestamp(const std::string& val) {
  this->timestamp = val;
}

void plan_confirm_info::__set_name(const std::string& val) {
  this->name = val;
}
std::ostream& operator<<(std::ostream& out, const plan_confirm_info& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t plan_confirm_info::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->timestamp);
          this->__isset.timestamp = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t plan_confirm_info::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("plan_confirm_info");

  xfer += oprot->writeFieldBegin("timestamp", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->timestamp);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(plan_confirm_info &a, plan_confirm_info &b) {
  using ::std::swap;
  swap(a.timestamp, b.timestamp);
  swap(a.name, b.name);
  swap(a.__isset, b.__isset);
}

plan_confirm_info::plan_confirm_info(const plan_confirm_info& other10) {
  timestamp = other10.timestamp;
  name = other10.name;
  __isset = other10.__isset;
}
plan_confirm_info& plan_confirm_info::operator=(const plan_confirm_info& other11) {
  timestamp = other11.timestamp;
  name = other11.name;
  __isset = other11.__isset;
  return *this;
}
void plan_confirm_info::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "plan_confirm_info(";
  out << "timestamp=" << to_string(timestamp);
  out << ", " << "name=" << to_string(name);
  out << ")";
}


pay_confirm_info::~pay_confirm_info() noexcept {
}


void pay_confirm_info::__set_timestamp(const std::string& val) {
  this->timestamp = val;
}

void pay_confirm_info::__set_name(const std::string& val) {
  this->name = val;
}
std::ostream& operator<<(std::ostream& out, const pay_confirm_info& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t pay_confirm_info::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->timestamp);
          this->__isset.timestamp = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t pay_confirm_info::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("pay_confirm_info");

  xfer += oprot->writeFieldBegin("timestamp", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->timestamp);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(pay_confirm_info &a, pay_confirm_info &b) {
  using ::std::swap;
  swap(a.timestamp, b.timestamp);
  swap(a.name, b.name);
  swap(a.__isset, b.__isset);
}

pay_confirm_info::pay_confirm_info(const pay_confirm_info& other12) {
  timestamp = other12.timestamp;
  name = other12.name;
  __isset = other12.__isset;
}
pay_confirm_info& pay_confirm_info::operator=(const pay_confirm_info& other13) {
  timestamp = other13.timestamp;
  name = other13.name;
  __isset = other13.__isset;
  return *this;
}
void pay_confirm_info::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "pay_confirm_info(";
  out << "timestamp=" << to_string(timestamp);
  out << ", " << "name=" << to_string(name);
  out << ")";
}


vichele_in_plan::~vichele_in_plan() noexcept {
}


void vichele_in_plan::__set_main_vichele(const std::string& val) {
  this->main_vichele = val;
}

void vichele_in_plan::__set_behind_vichele(const std::string& val) {
  this->behind_vichele = val;
}

void vichele_in_plan::__set_driver_name(const std::string& val) {
  this->driver_name = val;
}

void vichele_in_plan::__set_driver_phone(const std::string& val) {
  this->driver_phone = val;
}

void vichele_in_plan::__set_count(const double val) {
  this->count = val;
}

void vichele_in_plan::__set_drop_address(const std::string& val) {
  this->drop_address = val;
}

void vichele_in_plan::__set_use_for(const std::string& val) {
  this->use_for = val;
}
std::ostream& operator<<(std::ostream& out, const vichele_in_plan& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t vichele_in_plan::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->main_vichele);
          this->__isset.main_vichele = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->behind_vichele);
          this->__isset.behind_vichele = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->driver_name);
          this->__isset.driver_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->driver_phone);
          this->__isset.driver_phone = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->count);
          this->__isset.count = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->drop_address);
          this->__isset.drop_address = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->use_for);
          this->__isset.use_for = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t vichele_in_plan::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("vichele_in_plan");

  xfer += oprot->writeFieldBegin("main_vichele", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->main_vichele);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("behind_vichele", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->behind_vichele);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("driver_name", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->driver_name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("driver_phone", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->driver_phone);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("count", ::apache::thrift::protocol::T_DOUBLE, 5);
  xfer += oprot->writeDouble(this->count);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("drop_address", ::apache::thrift::protocol::T_STRING, 6);
  xfer += oprot->writeString(this->drop_address);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("use_for", ::apache::thrift::protocol::T_STRING, 7);
  xfer += oprot->writeString(this->use_for);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(vichele_in_plan &a, vichele_in_plan &b) {
  using ::std::swap;
  swap(a.main_vichele, b.main_vichele);
  swap(a.behind_vichele, b.behind_vichele);
  swap(a.driver_name, b.driver_name);
  swap(a.driver_phone, b.driver_phone);
  swap(a.count, b.count);
  swap(a.drop_address, b.drop_address);
  swap(a.use_for, b.use_for);
  swap(a.__isset, b.__isset);
}

vichele_in_plan::vichele_in_plan(const vichele_in_plan& other14) {
  main_vichele = other14.main_vichele;
  behind_vichele = other14.behind_vichele;
  driver_name = other14.driver_name;
  driver_phone = other14.driver_phone;
  count = other14.count;
  drop_address = other14.drop_address;
  use_for = other14.use_for;
  __isset = other14.__isset;
}
vichele_in_plan& vichele_in_plan::operator=(const vichele_in_plan& other15) {
  main_vichele = other15.main_vichele;
  behind_vichele = other15.behind_vichele;
  driver_name = other15.driver_name;
  driver_phone = other15.driver_phone;
  count = other15.count;
  drop_address = other15.drop_address;
  use_for = other15.use_for;
  __isset = other15.__isset;
  return *this;
}
void vichele_in_plan::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "vichele_in_plan(";
  out << "main_vichele=" << to_string(main_vichele);
  out << ", " << "behind_vichele=" << to_string(behind_vichele);
  out << ", " << "driver_name=" << to_string(driver_name);
  out << ", " << "driver_phone=" << to_string(driver_phone);
  out << ", " << "count=" << to_string(count);
  out << ", " << "drop_address=" << to_string(drop_address);
  out << ", " << "use_for=" << to_string(use_for);
  out << ")";
}


stuff_plan::~stuff_plan() noexcept {
}


void stuff_plan::__set_type_id(const int64_t val) {
  this->type_id = val;
}

void stuff_plan::__set_count(const double val) {
  this->count = val;
}

void stuff_plan::__set_vichele_info(const std::vector<vichele_in_plan> & val) {
  this->vichele_info = val;
}

void stuff_plan::__set_plan_id(const int64_t val) {
  this->plan_id = val;
}

void stuff_plan::__set_created_by(const int64_t val) {
  this->created_by = val;
}

void stuff_plan::__set_plan_time(const std::string& val) {
  this->plan_time = val;
}

void stuff_plan::__set_created_time(const int64_t val) {
  this->created_time = val;
}

void stuff_plan::__set_name(const std::string& val) {
  this->name = val;
}

void stuff_plan::__set_price(const double val) {
  this->price = val;
}

void stuff_plan::__set_status(const int64_t val) {
  this->status = val;
}

void stuff_plan::__set_comment(const std::string& val) {
  this->comment = val;
}

void stuff_plan::__set_plan_confirm(const plan_confirm_info& val) {
  this->plan_confirm = val;
}

void stuff_plan::__set_pay_confirm(const pay_confirm_info& val) {
  this->pay_confirm = val;
}

void stuff_plan::__set_pay_info(const std::string& val) {
  this->pay_info = val;
}

void stuff_plan::__set_pay_timestamp(const std::string& val) {
  this->pay_timestamp = val;
}

void stuff_plan::__set_close_timestamp(const std::string& val) {
  this->close_timestamp = val;
}

void stuff_plan::__set_close_by(const std::string& val) {
  this->close_by = val;
}
std::ostream& operator<<(std::ostream& out, const stuff_plan& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t stuff_plan::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->type_id);
          this->__isset.type_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->count);
          this->__isset.count = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->vichele_info.clear();
            uint32_t _size16;
            ::apache::thrift::protocol::TType _etype19;
            xfer += iprot->readListBegin(_etype19, _size16);
            this->vichele_info.resize(_size16);
            uint32_t _i20;
            for (_i20 = 0; _i20 < _size16; ++_i20)
            {
              xfer += this->vichele_info[_i20].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.vichele_info = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->plan_id);
          this->__isset.plan_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->created_by);
          this->__isset.created_by = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->plan_time);
          this->__isset.plan_time = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->created_time);
          this->__isset.created_time = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->price);
          this->__isset.price = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->comment);
          this->__isset.comment = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->plan_confirm.read(iprot);
          this->__isset.plan_confirm = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->pay_confirm.read(iprot);
          this->__isset.pay_confirm = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 14:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->pay_info);
          this->__isset.pay_info = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 15:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->pay_timestamp);
          this->__isset.pay_timestamp = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 16:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->close_timestamp);
          this->__isset.close_timestamp = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 17:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->close_by);
          this->__isset.close_by = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t stuff_plan::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("stuff_plan");

  xfer += oprot->writeFieldBegin("type_id", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->type_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("count", ::apache::thrift::protocol::T_DOUBLE, 2);
  xfer += oprot->writeDouble(this->count);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("vichele_info", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->vichele_info.size()));
    std::vector<vichele_in_plan> ::const_iterator _iter21;
    for (_iter21 = this->vichele_info.begin(); _iter21 != this->vichele_info.end(); ++_iter21)
    {
      xfer += (*_iter21).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("plan_id", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->plan_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("created_by", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->created_by);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("plan_time", ::apache::thrift::protocol::T_STRING, 6);
  xfer += oprot->writeString(this->plan_time);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("created_time", ::apache::thrift::protocol::T_I64, 7);
  xfer += oprot->writeI64(this->created_time);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 8);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("price", ::apache::thrift::protocol::T_DOUBLE, 9);
  xfer += oprot->writeDouble(this->price);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I64, 10);
  xfer += oprot->writeI64(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("comment", ::apache::thrift::protocol::T_STRING, 11);
  xfer += oprot->writeString(this->comment);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("plan_confirm", ::apache::thrift::protocol::T_STRUCT, 12);
  xfer += this->plan_confirm.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pay_confirm", ::apache::thrift::protocol::T_STRUCT, 13);
  xfer += this->pay_confirm.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pay_info", ::apache::thrift::protocol::T_STRING, 14);
  xfer += oprot->writeString(this->pay_info);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("pay_timestamp", ::apache::thrift::protocol::T_STRING, 15);
  xfer += oprot->writeString(this->pay_timestamp);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("close_timestamp", ::apache::thrift::protocol::T_STRING, 16);
  xfer += oprot->writeString(this->close_timestamp);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("close_by", ::apache::thrift::protocol::T_STRING, 17);
  xfer += oprot->writeString(this->close_by);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(stuff_plan &a, stuff_plan &b) {
  using ::std::swap;
  swap(a.type_id, b.type_id);
  swap(a.count, b.count);
  swap(a.vichele_info, b.vichele_info);
  swap(a.plan_id, b.plan_id);
  swap(a.created_by, b.created_by);
  swap(a.plan_time, b.plan_time);
  swap(a.created_time, b.created_time);
  swap(a.name, b.name);
  swap(a.price, b.price);
  swap(a.status, b.status);
  swap(a.comment, b.comment);
  swap(a.plan_confirm, b.plan_confirm);
  swap(a.pay_confirm, b.pay_confirm);
  swap(a.pay_info, b.pay_info);
  swap(a.pay_timestamp, b.pay_timestamp);
  swap(a.close_timestamp, b.close_timestamp);
  swap(a.close_by, b.close_by);
  swap(a.__isset, b.__isset);
}

stuff_plan::stuff_plan(const stuff_plan& other22) {
  type_id = other22.type_id;
  count = other22.count;
  vichele_info = other22.vichele_info;
  plan_id = other22.plan_id;
  created_by = other22.created_by;
  plan_time = other22.plan_time;
  created_time = other22.created_time;
  name = other22.name;
  price = other22.price;
  status = other22.status;
  comment = other22.comment;
  plan_confirm = other22.plan_confirm;
  pay_confirm = other22.pay_confirm;
  pay_info = other22.pay_info;
  pay_timestamp = other22.pay_timestamp;
  close_timestamp = other22.close_timestamp;
  close_by = other22.close_by;
  __isset = other22.__isset;
}
stuff_plan& stuff_plan::operator=(const stuff_plan& other23) {
  type_id = other23.type_id;
  count = other23.count;
  vichele_info = other23.vichele_info;
  plan_id = other23.plan_id;
  created_by = other23.created_by;
  plan_time = other23.plan_time;
  created_time = other23.created_time;
  name = other23.name;
  price = other23.price;
  status = other23.status;
  comment = other23.comment;
  plan_confirm = other23.plan_confirm;
  pay_confirm = other23.pay_confirm;
  pay_info = other23.pay_info;
  pay_timestamp = other23.pay_timestamp;
  close_timestamp = other23.close_timestamp;
  close_by = other23.close_by;
  __isset = other23.__isset;
  return *this;
}
void stuff_plan::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "stuff_plan(";
  out << "type_id=" << to_string(type_id);
  out << ", " << "count=" << to_string(count);
  out << ", " << "vichele_info=" << to_string(vichele_info);
  out << ", " << "plan_id=" << to_string(plan_id);
  out << ", " << "created_by=" << to_string(created_by);
  out << ", " << "plan_time=" << to_string(plan_time);
  out << ", " << "created_time=" << to_string(created_time);
  out << ", " << "name=" << to_string(name);
  out << ", " << "price=" << to_string(price);
  out << ", " << "status=" << to_string(status);
  out << ", " << "comment=" << to_string(comment);
  out << ", " << "plan_confirm=" << to_string(plan_confirm);
  out << ", " << "pay_confirm=" << to_string(pay_confirm);
  out << ", " << "pay_info=" << to_string(pay_info);
  out << ", " << "pay_timestamp=" << to_string(pay_timestamp);
  out << ", " << "close_timestamp=" << to_string(close_timestamp);
  out << ", " << "close_by=" << to_string(close_by);
  out << ")";
}


plan_status::~plan_status() noexcept {
}


void plan_status::__set_plan_id(const int64_t val) {
  this->plan_id = val;
}

void plan_status::__set_status(const int64_t val) {
  this->status = val;
}
std::ostream& operator<<(std::ostream& out, const plan_status& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t plan_status::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->plan_id);
          this->__isset.plan_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->status);
          this->__isset.status = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t plan_status::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("plan_status");

  xfer += oprot->writeFieldBegin("plan_id", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->plan_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("status", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->status);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(plan_status &a, plan_status &b) {
  using ::std::swap;
  swap(a.plan_id, b.plan_id);
  swap(a.status, b.status);
  swap(a.__isset, b.__isset);
}

plan_status::plan_status(const plan_status& other24) {
  plan_id = other24.plan_id;
  status = other24.status;
  __isset = other24.__isset;
}
plan_status& plan_status::operator=(const plan_status& other25) {
  plan_id = other25.plan_id;
  status = other25.status;
  __isset = other25.__isset;
  return *this;
}
void plan_status::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "plan_status(";
  out << "plan_id=" << to_string(plan_id);
  out << ", " << "status=" << to_string(status);
  out << ")";
}


