/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef user_management_H
#define user_management_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "idl_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class user_managementIf {
 public:
  virtual ~user_managementIf() {}
  virtual void get_user_info(user_info& _return, const std::string& ssid) = 0;
  virtual void user_login(std::string& _return, const std::string& code) = 0;
  virtual bool update_user_info(const user_info& info, const std::string& ssid) = 0;
  virtual bool remove_user(const int64_t user_id, const std::string& ssid) = 0;
};

class user_managementIfFactory {
 public:
  typedef user_managementIf Handler;

  virtual ~user_managementIfFactory() {}

  virtual user_managementIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(user_managementIf* /* handler */) = 0;
};

class user_managementIfSingletonFactory : virtual public user_managementIfFactory {
 public:
  user_managementIfSingletonFactory(const ::std::shared_ptr<user_managementIf>& iface) : iface_(iface) {}
  virtual ~user_managementIfSingletonFactory() {}

  virtual user_managementIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(user_managementIf* /* handler */) {}

 protected:
  ::std::shared_ptr<user_managementIf> iface_;
};

class user_managementNull : virtual public user_managementIf {
 public:
  virtual ~user_managementNull() {}
  void get_user_info(user_info& /* _return */, const std::string& /* ssid */) {
    return;
  }
  void user_login(std::string& /* _return */, const std::string& /* code */) {
    return;
  }
  bool update_user_info(const user_info& /* info */, const std::string& /* ssid */) {
    bool _return = false;
    return _return;
  }
  bool remove_user(const int64_t /* user_id */, const std::string& /* ssid */) {
    bool _return = false;
    return _return;
  }
};

typedef struct _user_management_get_user_info_args__isset {
  _user_management_get_user_info_args__isset() : ssid(false) {}
  bool ssid :1;
} _user_management_get_user_info_args__isset;

class user_management_get_user_info_args {
 public:

  user_management_get_user_info_args(const user_management_get_user_info_args&);
  user_management_get_user_info_args& operator=(const user_management_get_user_info_args&);
  user_management_get_user_info_args() : ssid() {
  }

  virtual ~user_management_get_user_info_args() noexcept;
  std::string ssid;

  _user_management_get_user_info_args__isset __isset;

  void __set_ssid(const std::string& val);

  bool operator == (const user_management_get_user_info_args & rhs) const
  {
    if (!(ssid == rhs.ssid))
      return false;
    return true;
  }
  bool operator != (const user_management_get_user_info_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const user_management_get_user_info_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class user_management_get_user_info_pargs {
 public:


  virtual ~user_management_get_user_info_pargs() noexcept;
  const std::string* ssid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _user_management_get_user_info_result__isset {
  _user_management_get_user_info_result__isset() : success(false) {}
  bool success :1;
} _user_management_get_user_info_result__isset;

class user_management_get_user_info_result {
 public:

  user_management_get_user_info_result(const user_management_get_user_info_result&);
  user_management_get_user_info_result& operator=(const user_management_get_user_info_result&);
  user_management_get_user_info_result() {
  }

  virtual ~user_management_get_user_info_result() noexcept;
  user_info success;

  _user_management_get_user_info_result__isset __isset;

  void __set_success(const user_info& val);

  bool operator == (const user_management_get_user_info_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const user_management_get_user_info_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const user_management_get_user_info_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _user_management_get_user_info_presult__isset {
  _user_management_get_user_info_presult__isset() : success(false) {}
  bool success :1;
} _user_management_get_user_info_presult__isset;

class user_management_get_user_info_presult {
 public:


  virtual ~user_management_get_user_info_presult() noexcept;
  user_info* success;

  _user_management_get_user_info_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _user_management_user_login_args__isset {
  _user_management_user_login_args__isset() : code(false) {}
  bool code :1;
} _user_management_user_login_args__isset;

class user_management_user_login_args {
 public:

  user_management_user_login_args(const user_management_user_login_args&);
  user_management_user_login_args& operator=(const user_management_user_login_args&);
  user_management_user_login_args() : code() {
  }

  virtual ~user_management_user_login_args() noexcept;
  std::string code;

  _user_management_user_login_args__isset __isset;

  void __set_code(const std::string& val);

  bool operator == (const user_management_user_login_args & rhs) const
  {
    if (!(code == rhs.code))
      return false;
    return true;
  }
  bool operator != (const user_management_user_login_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const user_management_user_login_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class user_management_user_login_pargs {
 public:


  virtual ~user_management_user_login_pargs() noexcept;
  const std::string* code;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _user_management_user_login_result__isset {
  _user_management_user_login_result__isset() : success(false) {}
  bool success :1;
} _user_management_user_login_result__isset;

class user_management_user_login_result {
 public:

  user_management_user_login_result(const user_management_user_login_result&);
  user_management_user_login_result& operator=(const user_management_user_login_result&);
  user_management_user_login_result() : success() {
  }

  virtual ~user_management_user_login_result() noexcept;
  std::string success;

  _user_management_user_login_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const user_management_user_login_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const user_management_user_login_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const user_management_user_login_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _user_management_user_login_presult__isset {
  _user_management_user_login_presult__isset() : success(false) {}
  bool success :1;
} _user_management_user_login_presult__isset;

class user_management_user_login_presult {
 public:


  virtual ~user_management_user_login_presult() noexcept;
  std::string* success;

  _user_management_user_login_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _user_management_update_user_info_args__isset {
  _user_management_update_user_info_args__isset() : info(false), ssid(false) {}
  bool info :1;
  bool ssid :1;
} _user_management_update_user_info_args__isset;

class user_management_update_user_info_args {
 public:

  user_management_update_user_info_args(const user_management_update_user_info_args&);
  user_management_update_user_info_args& operator=(const user_management_update_user_info_args&);
  user_management_update_user_info_args() : ssid() {
  }

  virtual ~user_management_update_user_info_args() noexcept;
  user_info info;
  std::string ssid;

  _user_management_update_user_info_args__isset __isset;

  void __set_info(const user_info& val);

  void __set_ssid(const std::string& val);

  bool operator == (const user_management_update_user_info_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    if (!(ssid == rhs.ssid))
      return false;
    return true;
  }
  bool operator != (const user_management_update_user_info_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const user_management_update_user_info_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class user_management_update_user_info_pargs {
 public:


  virtual ~user_management_update_user_info_pargs() noexcept;
  const user_info* info;
  const std::string* ssid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _user_management_update_user_info_result__isset {
  _user_management_update_user_info_result__isset() : success(false) {}
  bool success :1;
} _user_management_update_user_info_result__isset;

class user_management_update_user_info_result {
 public:

  user_management_update_user_info_result(const user_management_update_user_info_result&);
  user_management_update_user_info_result& operator=(const user_management_update_user_info_result&);
  user_management_update_user_info_result() : success(0) {
  }

  virtual ~user_management_update_user_info_result() noexcept;
  bool success;

  _user_management_update_user_info_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const user_management_update_user_info_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const user_management_update_user_info_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const user_management_update_user_info_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _user_management_update_user_info_presult__isset {
  _user_management_update_user_info_presult__isset() : success(false) {}
  bool success :1;
} _user_management_update_user_info_presult__isset;

class user_management_update_user_info_presult {
 public:


  virtual ~user_management_update_user_info_presult() noexcept;
  bool* success;

  _user_management_update_user_info_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _user_management_remove_user_args__isset {
  _user_management_remove_user_args__isset() : user_id(false), ssid(false) {}
  bool user_id :1;
  bool ssid :1;
} _user_management_remove_user_args__isset;

class user_management_remove_user_args {
 public:

  user_management_remove_user_args(const user_management_remove_user_args&);
  user_management_remove_user_args& operator=(const user_management_remove_user_args&);
  user_management_remove_user_args() : user_id(0), ssid() {
  }

  virtual ~user_management_remove_user_args() noexcept;
  int64_t user_id;
  std::string ssid;

  _user_management_remove_user_args__isset __isset;

  void __set_user_id(const int64_t val);

  void __set_ssid(const std::string& val);

  bool operator == (const user_management_remove_user_args & rhs) const
  {
    if (!(user_id == rhs.user_id))
      return false;
    if (!(ssid == rhs.ssid))
      return false;
    return true;
  }
  bool operator != (const user_management_remove_user_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const user_management_remove_user_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class user_management_remove_user_pargs {
 public:


  virtual ~user_management_remove_user_pargs() noexcept;
  const int64_t* user_id;
  const std::string* ssid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _user_management_remove_user_result__isset {
  _user_management_remove_user_result__isset() : success(false) {}
  bool success :1;
} _user_management_remove_user_result__isset;

class user_management_remove_user_result {
 public:

  user_management_remove_user_result(const user_management_remove_user_result&);
  user_management_remove_user_result& operator=(const user_management_remove_user_result&);
  user_management_remove_user_result() : success(0) {
  }

  virtual ~user_management_remove_user_result() noexcept;
  bool success;

  _user_management_remove_user_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const user_management_remove_user_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const user_management_remove_user_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const user_management_remove_user_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _user_management_remove_user_presult__isset {
  _user_management_remove_user_presult__isset() : success(false) {}
  bool success :1;
} _user_management_remove_user_presult__isset;

class user_management_remove_user_presult {
 public:


  virtual ~user_management_remove_user_presult() noexcept;
  bool* success;

  _user_management_remove_user_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class user_managementClient : virtual public user_managementIf {
 public:
  user_managementClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  user_managementClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get_user_info(user_info& _return, const std::string& ssid);
  void send_get_user_info(const std::string& ssid);
  void recv_get_user_info(user_info& _return);
  void user_login(std::string& _return, const std::string& code);
  void send_user_login(const std::string& code);
  void recv_user_login(std::string& _return);
  bool update_user_info(const user_info& info, const std::string& ssid);
  void send_update_user_info(const user_info& info, const std::string& ssid);
  bool recv_update_user_info();
  bool remove_user(const int64_t user_id, const std::string& ssid);
  void send_remove_user(const int64_t user_id, const std::string& ssid);
  bool recv_remove_user();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class user_managementProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<user_managementIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (user_managementProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_get_user_info(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_user_login(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_update_user_info(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_remove_user(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  user_managementProcessor(::std::shared_ptr<user_managementIf> iface) :
    iface_(iface) {
    processMap_["get_user_info"] = &user_managementProcessor::process_get_user_info;
    processMap_["user_login"] = &user_managementProcessor::process_user_login;
    processMap_["update_user_info"] = &user_managementProcessor::process_update_user_info;
    processMap_["remove_user"] = &user_managementProcessor::process_remove_user;
  }

  virtual ~user_managementProcessor() {}
};

class user_managementProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  user_managementProcessorFactory(const ::std::shared_ptr< user_managementIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< user_managementIfFactory > handlerFactory_;
};

class user_managementMultiface : virtual public user_managementIf {
 public:
  user_managementMultiface(std::vector<std::shared_ptr<user_managementIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~user_managementMultiface() {}
 protected:
  std::vector<std::shared_ptr<user_managementIf> > ifaces_;
  user_managementMultiface() {}
  void add(::std::shared_ptr<user_managementIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void get_user_info(user_info& _return, const std::string& ssid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_user_info(_return, ssid);
    }
    ifaces_[i]->get_user_info(_return, ssid);
    return;
  }

  void user_login(std::string& _return, const std::string& code) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->user_login(_return, code);
    }
    ifaces_[i]->user_login(_return, code);
    return;
  }

  bool update_user_info(const user_info& info, const std::string& ssid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->update_user_info(info, ssid);
    }
    return ifaces_[i]->update_user_info(info, ssid);
  }

  bool remove_user(const int64_t user_id, const std::string& ssid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->remove_user(user_id, ssid);
    }
    return ifaces_[i]->remove_user(user_id, ssid);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class user_managementConcurrentClient : virtual public user_managementIf {
 public:
  user_managementConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  user_managementConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get_user_info(user_info& _return, const std::string& ssid);
  int32_t send_get_user_info(const std::string& ssid);
  void recv_get_user_info(user_info& _return, const int32_t seqid);
  void user_login(std::string& _return, const std::string& code);
  int32_t send_user_login(const std::string& code);
  void recv_user_login(std::string& _return, const int32_t seqid);
  bool update_user_info(const user_info& info, const std::string& ssid);
  int32_t send_update_user_info(const user_info& info, const std::string& ssid);
  bool recv_update_user_info(const int32_t seqid);
  bool remove_user(const int64_t user_id, const std::string& ssid);
  int32_t send_remove_user(const int64_t user_id, const std::string& ssid);
  bool recv_remove_user(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
