// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "pa_rest.h"
#include "../../../pa_lib/pa_api.h"

std::string pa_rest::echo(const std::string& text)
{
    auto resp = PA_API_proc_test_echo(text);
    return "Hi, " + resp;
}


rest_userinfo pa_rest::proc_get_userinfo(const std::string& pa_ssid)
{
    rest_userinfo ret;
    auto result = PA_API_proc_get_userinfo(pa_ssid);
    if (result)
    {
        ret.name = result->m_name;
        ret.company = result->m_company;
        ret.logo = result->m_logo;
        ret.role = result->m_role;
        ret.online = true;
    }

    return ret;
}
std::string pa_rest::proc_post_wechat_login(const std::string& code)
{
    return PA_API_proc_wechat_login(code);
}