// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "pa_rest.h"
#include "../../../pa_lib/pa_api.h"
#include <thread>

#define LOG_CURRENT_REQ(format, ...) g_log.log("calling %s with " format,__func__, ##__VA_ARGS__)

static tdf_log g_log("pa_rest");
std::string pa_rest::echo(const std::string& text)
{
    auto resp = PA_API_proc_test_echo(text);
    return "Hi, " + resp;
}


rest_userinfo pa_rest::proc_get_userinfo(const std::string& pa_ssid)
{
    rest_userinfo ret;

    ret.online = false;
    auto result = PA_API_proc_get_userinfo(pa_ssid);
    if (result)
    {
        ret.name = result->m_name;
        ret.company = result->m_company;
        ret.logo = result->m_logo;
        ret.role = result->m_role;
        ret.online = true;
    }

    return ret;
}

void pa_rest::proc_post_wechat_login_async(const std::string& code, ngrest::Callback<const std::string&>& callback)
{
    LOG_CURRENT_REQ("code : %s", code.c_str());

    std::thread([&callback, code]{
        auto ret = PA_API_proc_wechat_login(code);
        ngrest::Handler::post([&callback, ret]{
            callback.success(ret);
        });
    }).detach();
}